[package]
name = "krets-parser"
version = "0.1.2"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
nom = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
log = { workspace = true }
